name: OpenAI API Test

on:
  push:
    branches:
      - main  # or your branch name
  workflow_dispatch:  # allows you to trigger manually from the GitHub UI

jobs:
  test-openai-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run OpenAI test script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "
import openai
openai.api_key = '${{ secrets.OPENAI_API_KEY }}'
response = openai.Model.list()
print(response)
"
